apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgresCredentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: my-test-store
    kind: ClusterSecretStore
  target:
    template:
      data:
        password: '{{ .password }}'
        postgresUsername: '{{ .postgresUsername }}'
        postgresUsername2: '{{ .postgresUsername }}'
        pwd: pwd
  data:
    - secretKey: password
      remoteRef:
        key: password
    - secretKey: postgresUsername
      remoteRef:
        key: postgresUsername
---
