apiVersion: v1
kind: Secret
metadata:
  annotation:
    some-annotation: nope
    some-other-annotation: yihoo
  labels:
    some-label: yup
    some-other-label: nope
  name: mariadbCredentials
  namespace: default
stringData:
  invalidThing: '{{ somethingInvalid }}'
type: Opaque
---
